summary: "Requisição do Firebase"
description: "Rota ligada diretamente do banco não-relacional do Firebase"
consumes:
- "application/json"
produces:
- "application/json"
parameters:
- in: "Clientes"
  name: "JSON"
  description: "JSON com a lista de clientes"
  required: true
  schema:
    type: "object"
    properties:
      nome:
        type: "string"
        format: "text"
        example: 'User'
      telefone:
        type: "string"
        format: "text"
        example: '99999-9999'
      email:
        type: "string"
        format: "text"
        example: 'email@domain.com'
      endereco:
        type: "string"
        format: "text"
        example: "Bairro, Cidade - Estado"
      profissao:
        type: "string"
        format: "text"
        example: "Developer"
      curriculo:
        type: "string"
        format: "text"
        example: "curriculo.pdf"
responses:
  405:
    description: "Invalid input"
  200:
    description: "Successful operation"
  500:
    description: "Connection close"